### ISSUE TITLE
Catalog query fixes - vizier timeout, better external user support

### ISSUE THREAD

**Issue by olyoberdorf** [GeminiDRSoftware/DRAGONS#334]
DRAGONS has some code for querying external catalogs.  This has a few issues that Chris pointed out to me:

gempy.gemini.gemini_catalog_client: so I was running addReferenceCatalog() on an image and it reported
   No results returned from 2mass_mko
   No results returned from 2mass_vizier
   No reference catalog sources found for S20130522S0084_skyCorrected.fits
then I ran it again and it reported
   No results returned from 2mass_mko
   Found 516 reference catalog sources for S20130522S0084_skyCorrected.fits
So, a couple of things here. First and most obviously, the Vizier search worked the second time but not the first. My guess is that this is a timeout being set too short for Vizier (it's in France, they're often on strike). I see that this is modifiable and the default is 30s but some trial and error will be needed to determine a better value. The second thing is that the 2mass_mko server isn't returning results because the URL is looking for a network address called mkocatalog2 which is unknown outside the firewall. I'm not sure if this machine is accessible outside the firewall (probably not) so can we improve the logging to indicate "machine not reachable" rather than "no results returned"? I don't know if astroquery returns anything to differentiate between these cases. Third, GMOS uses the "gmos" catalogue, which is only internal, so we should probably add "sdss9_vizier" to the CAT_SERVERS list so people outside Gemini can get something for GMOS.
Finally, the code is pretty grim. The CAT_COLS and SERVER_COLMAP have lots of repetition; if you fancy cleaning it up, have at it! (But be careful of course, since it ain't broke -- you might want to beef up the test a little to check that the column name translations are done).
Can you take a look please? This isn't urgent, since obviously I can just keep running addReferenceCatalog on my data until it works.

**Comment by chris-simpson** [comment]
This has largely been fixed (at least in terms of improved logging) in commits d6d385a and b0a29e7 so I'm closing the issue.
