### ISSUE TITLE
The shifts for shiftImages should allow any number/type of spaces

### ISSUE THREAD

**Issue by KathleenLabrie** [GeminiDRSoftware/DRAGONS#365]
Currently, the x, y shifts must be separated by exactly one space.  One space, two spaces, 10 spaces, a tab, whatever, should work just the same.  The split currently splits on " ", just one space.  A "re" could be use instead.

**Comment by chris-simpson** [comment]
Fixed in this commit for spaces and tabs: 50d0ab82e11704f07e5d3a83df44b68ce3b3264e
