### ISSUE TITLE
skySubtract gets into an infinite loop

### ISSUE THREAD

**Issue by KathleenLabrie** [GeminiDRSoftware/DRAGONS#388]
This is a new behavior.  The same call on the same data has been working fine for years, (DRAGONS v2 and DRAGONS v3.0.x)

Data here:  https://drive.google.com/drive/folders/15YgYnOAdvuM_XWwaZWoLZHmuT4hTRkbh?usp=sharing

Call:
`reduce -r skyCorrect @debug.lis -p mask_objects=False reject_method=varclip`

Observed to fail on both Mac OS X and Linux.

**Comment by KathleenLabrie** [comment]
Forgot to be specific about the branch:  `release/3.1.x`

**Comment by chris-simpson** [comment]
It appears to happen on `master` too

**Comment by chris-simpson** [comment]
fix pushed to `bugfix/skysub_infinite_loop` which will need to be merged into both `master` and `release/3.1.x` if tests pass

**Comment by chris-simpson** [comment]
tests pass, commit implemented in both branches, closing issue

**Comment by chris-simpson** [comment]
I realize there are other edge cases which aren't handled properly so I'm reopening this

**Comment by chris-simpson** [comment]
Should be OK now. There was an issue where all the skies were single frames and you were doing something like subtracting B from A and A from B where you can't sky-subtract either "in place" without messing up the other subtraction.

**Comment by chris-simpson** [comment]
All good. Closing ticket again.
