### ISSUE TITLE
measureIQ does not find nice source almost centered in the slit

### ISSUE THREAD

**Issue by KathleenLabrie** [GeminiDRSoftware/DRAGONS#390]
Older versions were finding the source and measuring IQ.  In release/3.1.x, it claims no good sources.  See screenshot.
![Screen Shot 2022-09-28 at 14 23 14](https://user-images.githubusercontent.com/2152829/192911335-00a82c4e-f1f5-446d-9b3f-ead3bd76599e.png)

Data:  https://drive.google.com/drive/folders/1O0DyGs5PZ6ivXpOvhWu4CW6LGrE-A6HJ?usp=sharing
Run: `reduce -r measureIQ N20180521S0099_ADUToElectrons.fits`

**Comment by chris-simpson** [comment]
Oops. This is a refactoring error on my part that accidentally missed out some functionality in an effort to improve efficiency. It's not trivial to sort out.

**Comment by chris-simpson** [comment]
Fix and tidy in new branch `bugfix/measureiq_ls` from `master`. Waiting for tests and will cherry-pick into `release/3.1.x`

**Comment by chris-simpson** [comment]
Now in both `master` and `release/3.1.x`. Tests pending.

**Comment by chris-simpson** [comment]
Tests passed. Closing ticket.
