### ISSUE TITLE
Spatial alignment fails for GMOS longslit

### ISSUE THREAD

**Issue by KathleenLabrie** [GeminiDRSoftware/DRAGONS#397]
Data (_skyCorrected, ready for the alignment primitives): https://drive.google.com/drive/folders/19uitWlEjEiyRZsQAX3F4xGxlsTjCCs6A?usp=sharing

(data is still proprietary, the link is restricted.)

The sequence is a  sci-sci / flat-flat / sci-sci / flat / sci-sci.    (the flats are not included in the data package)  The spatial offset is 93.5 pixels (15" with 2pix binning).   The sci-sci are all offsetted correctly between themselves, but the first sci-sci is offset compared to the other two (about 10pix), as if something jumped when the first flat-flat was taken.

The `adjustWCSToReference` cross-correlation to find the peaks and ensure precise aligned is failing, and the WCS is used directly which would be fine if it were not for that 10 pix jump. 

Why is the cross-correlation failing is the big question here.   The data is "bad amp 5" data, maybe that's the source?  It is masked though.  The illumination mask is aligned correctly, so that's not it either.   Maybe `adjustWCS...` does use the mask and the bad amp trips the cross-correlation?

**Comment by chris-simpson** [comment]
This is not an issue. There's a "tolerance" parameter for alignment which has a default of 1 arcsecond. If you set it to something like 3 arcseconds, to account for the "extra" 10 pixel shift, everything works fine. We can discuss what the default *should* be but the code does what it's designed to do. Closing.
