### ISSUE TITLE
QECorrect Primitive not working on Longslit E2V data v 3.1

### ISSUE THREAD

**Issue by jendrews83** [GeminiDRSoftware/DRAGONS#446]
I'm working on GMOS-S longslit from 2012 (GS-2012A-79) and can reduce biases, flats, and arcs but when it gets to the reduction of the standard or science it bombs on the QECorrect Primitive step. I've successfully reduced Ham longslit with this install, and imaging with E2V from this same dataset, but can't seem to get E2V longslit to work.  I'm attaching the log file for reference.
[reduce.log](https://github.com/GeminiDRSoftware/DRAGONS/files/14070411/reduce.log)

**Comment by chris-simpson** [comment]
This has been fixed in the release/3.1.x branch with commit ac2e4287d17f8d931689c45176854e2cc35b178c but we haven't put out a patch.
